---
- name: Run a webhook listener service for ServiceNow integration tests
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5005
  rules:
    - name: ServiceNow Incident
      condition: event.payload.number is search("INC", ignorecase=false)
      action:
        debug:
          msg: "ServiceNow Incident received!"

    - name: ServiceNow Problem
      condition: event.payload.number is search("PRB", ignorecase=false)
      action:
        debug:
          msg: "ServiceNow Problem received!"

    - name: ServiceNow Catalog Request
      condition: event.payload.number is search("REQ", ignorecase=false)
      action:
        debug:
          msg: "ServiceNow Catalog Request received!"

    - name: Shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
